# Whenever a push is made to the master branch then run the job
on: 
  push:
    branches:
      - master

jobs:
  # job id, can be anything
  # export_game:

        # GITHUB_TOKEN: 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